[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
s_ledger_contracts = "35qvfT4uVxegmX6LpkJdFAvSBkDUmrHrqDB1N6ZWmcV4"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
